version: '3.8'
 
services:
 
  elgamal-algorithm:
    container_name: elgamal-algorithm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true